[[headers]]
  for = "/*"
  [headers.values]
    Permission-Policy = "interest-cohort=()"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[context.deploy-preview]
  command = "zola build --drafts"

[[redirects]]
  from = "/post"
  to = "/"
  force = true
